#!/bin/sh

# This script makes anacron jobs start to run when the machine is woken up.
# For a laptop, these are the closest parallels to turning on a desktop.

case $1/$2 in
    post/*)
        modprobe -r wacom
        modprobe -r wacom_w8001
        modprobe wacom
        modprobe wacom_w8001
esac
